trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # Microsoft-hosted agent

variables:
  TF_VERSION: '1.13.3'       # Latest stable Terraform version

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: $(TF_VERSION)

- script: |
    echo "🔧 Initializing Terraform..."
    terraform init
  displayName: 'Terraform Init'

- script: |
    echo "📐 Planning Terraform deployment..."
    terraform plan -var-file="terraform.tfvars"
  displayName: 'Terraform Plan'

- script: |
    echo "🚀 Applying Terraform changes..."
    terraform apply -var-file="terraform.tfvars" -auto-approve
  displayName: 'Terraform Apply'