trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.13.3'
  azureServiceConnection: 'Landing-zone'   # update if your service connection name differs

steps:
- checkout: self

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '$(TF_VERSION)'

- task: AzureCLI@2
  displayName: 'Terraform: init → plan → apply'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd "$(System.DefaultWorkingDirectory)"
      terraform init -reconfigure
      terraform plan -out=tfplan -input=false
      terraform apply -auto-approve tfplan
