trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TerraformPlan
  jobs:
  - job: Plan
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - script: |
        terraform init
        terraform plan -out=tfplan
      displayName: 'Terraform Init and Plan'
    - publish: tfplan
      artifact: tfplan

- stage: TerraformApply
  dependsOn: TerraformPlan
  condition: succeeded()
  jobs:
  - job: Apply
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - download: current
      artifact: tfplan
    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
