trigger:
  branches:
    include:
      - main

variables:
  terraformVersion: '1.6.0'
  azureServiceConnection: 'Your-Service-Connection-Name'
  backendResourceGroup: 'tfstate-rg'
  backendStorageAccount: 'tfstateaccount'
  backendContainerName: 'tfstate'
  backendKey: 'terraform.tfstate'

pool:
  name: 'Default'

stages:
- stage: Terraform_Init
  jobs:
  - job: Init
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $terraformZip = "terraform_${env:terraformVersion}_windows_amd64.zip"
          Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/$($env:terraformVersion)/$terraformZip" -OutFile $terraformZip
          Expand-Archive -Path $terraformZip -DestinationPath "$env:USERPROFILE\terraform"
          $env:Path += ";$env:USERPROFILE\terraform"
          terraform version
          terraform init `
            -backend-config="resource_group_name=$(backendResourceGroup)" `
            -backend-config="storage_account_name=$(backendStorageAccount)" `
            -backend-config="container_name=$(backendContainerName)" `
            -backend-config="key=$(backendKey)"
      displayName: 'Install Terraform and Init with Azure Service Connection'

- stage: Terraform_Plan
  dependsOn: Terraform_Init
  jobs:
  - job: Plan
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    - publish: tfplan
      artifact: terraformPlan

- stage: Terraform_Apply
  dependsOn: Terraform_Plan
  condition: succeeded()
  jobs:
  - job: Apply
    steps:
    - download: current
      artifact: terraformPlan

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'