trigger:
  branches: [ main ]

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.5.7'

steps:
- checkout: self

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '$(TF_VERSION)'

- script: |
    cd $(System.DefaultWorkingDirectory)
    terraform init -reconfigure
    terraform plan -var-file="terraform.tfvars" -out=tfplan -input=false
    terraform apply -auto-approve tfplan
  displayName: 'Init • Plan • Apply'
